name: BUILD-NINTENDO_WII-ROM

on:
  push:
   paths:
   - '.github/workflows/build-wii-rom.yml'
   - '240psuite/Wii/**'
  pull_request:
   paths:
   - '.github/workflows/build-wii-rom.yml'
   - '240psuite/Wii/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        # sudo apt update
        # sudo apt upgrade
        sudo apt-get install -y build-essential git libpng-dev gdebi-core

    - name: Download and install extra dependencies
      run: |
        curl -L https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb > devkitpro-pacman.amd64.deb
        sudo gdebi --n devkitpro-pacman.amd64.deb

    - name: Install SDK
      run: |
        sudo pacman -Sy
        sudo pacman -S wii-dev

    - name: Build ROM
      run: |
        cd ${{ github.workspace }}/240psuite/Wii/
        # gcc tools/cfile.c -o cfile 
        make -f Makefile.wii

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_WII-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Wii/*.dol
