name: BUILD-NINTENDO_WII-ROM

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        # sudo apt-get install libz
        sudo apt-get install gdebi-core
        sudo gdebi devkitpro-pacman.deb

    - name: Install SDK
      run: |
        sudo pacman -S wii-dev

    - name: Build ROM
      run: |
        cd ${{ github.workspace }}/240psuite/Wii/
        # gcc tools/cfile.c -o cfile 
        make -f Makefile.wii

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_WII-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Wii/*.WIA
