name: BUILD-NINTENDO_WII-ROM

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build ROM
      run: |
        cd ${{ github.workspace }}/240psuite/Wii/
        make wii

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_WII-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Wii/*.WIA
